import type { Metadata } from "next";
import { poppins } from "./fonts";

import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Alexis Rodrigues | Marketing Digital Freelancer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-background flex justify-center ${poppins.className}`}
      >
        <div className="w-11/12">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
